- name: Exo 1 version 2
  hosts: slaves
  gather_facts: no

  tasks:
  - name: Installe nodejs et npm
    become: yes
    apt:
      name: nodejs,npm
      update_cache: yes
      state: present
  
  - name: Git clonage
    git:
      repo: https://gitlab.com/cdufour1/nodeapp.git
      dest: ~/nodeapp
  
  - name: Installe les dépendances
    shell: npm install 
    args:
      chdir: nodeapp
  
  - name: Exécute le serveur web (app.js)
    shell: nohup node nodeapp/app.js 2>error.txt & # détachement du child process